name: neo4j_todos_data_source
description: An neo4j implementation of the TodosDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  todos_data_source:
    path: ../todos_data_source
  uuid: ^3.0.6
  neo4driver: ^1.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
